### ISSUE TITLE
pretrain weights polyformer_b shows bad metrics

### ISSUE THREAD

**Issue by IL98** [amazon-science/polygon-transformer#10]
Hello! I've downloaded pretrain weights from [link](https://drive.google.com/file/d/1sAzfChYDdHdaeatB2K14lrJjG4uiXAol/view?usp=share_link) at Readme.md. Then I've run script evaluate_polyformer_b_refcoco.sh on refcoco_testA using these weights, and recieve the results with zero metrics.
I've tried to tune this checkpoint weights, and after the evaluation I've recieved much better metrics.
Seems like weights from link are random weights :(
Could you send the link to the pretrained weigths please? Maybe I didn't find right weights(

**Comment by joellliu** [comment]
Hi, the pretrain weights are the checkpoint after the first stage fine-tuning on the referring expression comprehension task. You should use the checkpoint listed in the tables which are fine-tuned on both referring expression comprehension and referring image segmentation.
