### ISSUE TITLE
The length(t) of polygon vertex sequence in paper?

### ISSUE THREAD

**Issue by zebbsb** [amazon-science/polygon-transformer#16]
Thanks for your brilliant work! It confuses me that how polyformer determines the length of predicted polygon vertex sequences? In equation (5), the sequence number of each vertex is represented by 't'. In section of Polygon Representation, 'K' is used for representing the total num of vertex. However, t_poly is not fixed in Fig,8.

**Comment by joellliu** [comment]
Hi, the length of the sequence is not fixed. The prediction ends when the eos token is predicted.

**Comment by zebbsb** [comment]
> Hi, the length of the sequence is not fixed. The prediction ends when the eos token is predicted.

Thanks for your answer!
I noticed it in Prediction Heads section: The prediction of the 2D coodinate of  vertex is produced by sending the Q^N, which is generated by transformer decoder in Fig 4, to Coordinate Head for a result, and then process the result by sigmoid function for final prediction of coordinate. 
Is the shape of Q^N still the same as the shape of (H*W/32) of F_M?
What's more, is this step to get the relative coordinates, between [0,1] (x, y), of the vertex? Or performing the binary classification for each location on FFN(Q^N). Only the positive vertex can combine the (x,y) of location to generate the coordinate prediction of this point? 

I would greatly appreciate it if you could point out where the code for the two heads is in the project.

**Comment by joellliu** [comment]
1. No, the shape of  Q^N will be the same as the input to the transformer decoder. 
2. Yes the outputs of the coordinate head are relative coordinates between [0,1] (Eq.4).
3. The two heads are defined here
https://github.com/amazon-science/polygon-transformer/blob/69fc728b2ec6a2b3595ec34db64074badcb19151/models/polyformer/unify_transformer.py#L1051

**Comment by vvuonghn** [comment]
Hi, 
This is an interesting discussion. I have a question about the token-embedding, How the computer/model can understand BOS... SEP ... EOS. I got your idea, but how to implementation for the computer can understand.
Could you show me the way you convert from the list (x,y) to the token.
I would greatly appreciate your response!

**Comment by zebbsb** [comment]
> Hi, This is an interesting discussion. I have a question about the token-embedding, How the computer/model can understand BOS... SEP ... EOS. I got your idea, but how to implementation for the computer can understand. Could you show me the way you convert from the list (x,y) to the token. I would greatly appreciate your response!

@vvuonghn Hello, in my aspect (and in the part of base_decoder.py), the list of coords (x,y) is provided by ground truth, but BOS and other indicators are attached before decoding. GT provides the list of polygon, while some masks are presented in multidimensional lists (e.g. a list contains 4 sublist) to illustrate objects with many parts. BOS and EOS are attached to both ends of seq. SEP is attached between each sublists. They are 'labelled' and have own classification indicator (0, 1, 2, I assume). So model can learn how to classify the input feature (numerical value generated by encoder with the (x,y) you mentioned and pixel value) into a classification result. So dose the coord prediction ( a regression result).

**Comment by vvuonghn** [comment]
Hi @zebbsb 
Could you share me the file you are mention, I checked in .fairseq/examples/speech_recognition/new/decoders/base_decoder.py
But there is no func was called

I think the function for BOS SEP EOS in `/data/refcoco_dataset.py` https://github.com/amazon-science/polygon-transformer/blob/69fc728b2ec6a2b3595ec34db64074badcb19151/data/refcoco_dataset.py#L76

Btw @joellliu , why do we need the `quant_box = region_points * (self.num_bins - 1)` https://github.com/amazon-science/polygon-transformer/blob/69fc728b2ec6a2b3595ec34db64074badcb19151/data/refcoco_dataset.py#L123  and `quant_poly = [poly * (self.num_bins - 1) for poly in polygons_scaled]` https://github.com/amazon-science/polygon-transformer/blob/69fc728b2ec6a2b3595ec34db64074badcb19151/data/refcoco_dataset.py#L129

What is the motivation when we do quantization
