### ISSUE TITLE
There is a problem with the website address

### ISSUE THREAD

**Issue by GreaBugs** [amazon-science/polygon-transformer#2]
Hello, **http://bvisionweb1.cs.unc.edu/licheng/referit/data/images/saiapr_tc-12.zip** and Download MSCOCO from **mscoco**
Are these two websites invalid?

**Comment by joellliu** [comment]
Hi, can you try these two links?

http://images.cocodataset.org/zips/train2014.zip

https://drive.google.com/file/d/1R6Tm7tQTHCil6A_eOhjudK3rgaBxkD2t

**Comment by GreaBugs** [comment]
mscoco is train2014.zip. But the second one should be  a subset of saiapr_tc-12? You mentioned in refer/data/README.md

**Comment by GreaBugs** [comment]
Both of these links can be used, but are both the original dataset and not the subset you extracted?

**Comment by joellliu** [comment]
The subsets will be extracted in the data processing and loading codes.

**Comment by GreaBugs** [comment]
Okay, thank you. I'll give it a try when I have time. And your ideas are great.

**Comment by joellliu** [comment]
Thank you!

**Comment by lmsdss** [comment]
Hello, I wanted to bring to your attention that I have noticed the Visual Genome images dataset link is currently invalid. When trying to access it, I encountered an error message indicating that the link is not working.

**Comment by joellliu** [comment]
> Hello, I wanted to bring to your attention that I have noticed the Visual Genome images dataset link is currently invalid. When trying to access it, I encountered an error message indicating that the link is not working.

Thank you for letting us know. Indeed the visual genome website is down. Alternatively, you can use the following links to download the visual genome images:

https://cs.stanford.edu/people/rak248/VG_100K_2/images.zip
 https://cs.stanford.edu/people/rak248/VG_100K_2/images2.zip
