### ISSUE TITLE
About Regression-based Transformer Decoder

### ISSUE THREAD

**Issue by vvuonghn** [amazon-science/polygon-transformer#21]
Hi,
Thank you for your work. This paper is very interested
I would like to know more about Regression-based Transformer Decoder. In Fingure 2 (Regression-based Transformer Decoder block), the input include <BOS>...<SEP>...
<img width="1298" alt="image" src="https://github.com/amazon-science/polygon-transformer/assets/34616024/dce7de4e-6c9e-4895-99b1-0891c3aed745">
In case inference new dataset, how do we know about the new coordination x,y for polygons

**Comment by joellliu** [comment]
Hi, during inference we first input the BOS token and predict the rest of the tokens including the polygon coordinates in an autoregressive way. Check out the animation on the project website for illustration https://polyformer.github.io/.

**Comment by vvuonghn** [comment]
Hi,
you means the output of multi-modal transformer encoder is token <BOS>...<SPE>... and the output of Regression-based Transformer Decoder is the rest of the tokens including the polygon coordinates

**Comment by joellliu** [comment]
No the outputs of the Transformer encoder are feature embeddings of the input image and text. The inputs to the  Transformer decoder are the feature embeddings and all previously predicted tokens (mostly polygon coordinates).

**Comment by vvuonghn** [comment]
Yeah, I got your point
Could I confirm for the Regression-based Transformer Decoder block, 
* first you init <BOS> then inference (x1,y1), 
* then (x1,y1) as an input for Regression-based Transformer Decoder block again -> the output is (x2,y2)
...
output at t, input at t-1

**Comment by joellliu** [comment]
At step T, the input will be all previous predictions (t=0, ..., T-1)

**Comment by vvuonghn** [comment]
Thank you so much for your explanation; it is a great idea!
By the way, is the process for the Regression-based Transformer Decoder the same in training and inference? And is the number of input tokens static, or is it flexible depending on each sample? Because the number object per image is not static.

**Comment by joellliu** [comment]
No. In training, we input the whole sequence t = 0, .., T-1 and use t = 1, ..., T as the ground truth for computing the loss. The number of input tokens is flexible, but we have set a maximum length in our code.

**Comment by vvuonghn** [comment]
Thank you so much! Great work

**Comment by vvuonghn** [comment]
Hi @joellliu 

```At step T, the input will be all previous predictions (t=0, ..., T-1)``` is the process is the same in training and inference?
and also, if you object have more than one polygon, example you have 3 polygon. so the sequence token contain 3 polygon. so when we predict corner for the polygon 3rd, Does we use the first polygon token?
