### ISSUE TITLE
Help, please! When I run bash evaluate_polyformer_l_refcoco.sh, an error has occurred:OSError: Can't load config for 'bert-base-uncased'. Make sure that:

### ISSUE THREAD

**Issue by ustczhouyu** [amazon-science/polygon-transformer#24]
File "/data/zhou/polygon-transformer/bert/configuration_utils.py", line 201, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/data/zhou/polygon-transformer/bert/configuration_utils.py", line 252, in get_config_dict
    raise EnvironmentError(msg)
OSError: Can't load config for 'bert-base-uncased'. Make sure that:

- 'bert-base-uncased' is a correct model identifier listed on 'https://huggingface.co/models'

- or 'bert-base-uncased' is the correct path to a directory containing a config.json file

**How should I solve this problem? Please help me. @hyandell @orchidmajumder @usbhub @yzou2 @zhaoweicai

**Comment by joellliu** [comment]
Hi, I think this might be related to connection issue with huggingface. Can you confirm if you can connect to huggingface on your machine?
