### ISSUE TITLE
About the pre-processed tsv files

### ISSUE THREAD

**Issue by qumengxue** [amazon-science/polygon-transformer#3]
Excellent work, thank you for the open source! 
But I meet with some problems. I can't install the 'refer', I'm not sure whether it's because of the version issue. 
Can you please provide the preprocessed **_tsv_** files?

**Comment by joellliu** [comment]
Hi @qumengxue, can you describe what issue you have with 'refer'? Technically you don't need to install it, but you may need to run the setup step as described here

https://github.com/amazon-science/polygon-transformer/tree/main/refer#setup

**Comment by qumengxue** [comment]
> Hi @qumengxue, can you describe what issue you have with 'refer'? Technically you don't need to install it, but you may need to run the setup step as described here
> 
> https://github.com/amazon-science/polygon-transformer/tree/main/refer#setup

Thanks for your quick reply, I reinstalled 'refer' and successfully generated the tsv file.

**Comment by LFUSST** [comment]
Hello, qumengxue， how is the problem of  'refer' solved ?

**Comment by LFUSST** [comment]
Hi @qumengxue, how did you solve this problem, please
