### ISSUE TITLE
About the generation of 2D coordinates codebook

### ISSUE THREAD

**Issue by LinfengYuan1997** [amazon-science/polygon-transformer#5]
Thanks for your excellent work!

I am wondering how to produce the embedding codebook for integer 2D coordinates. Maybe sin positional embedding?

**Comment by joellliu** [comment]
Hi, in our work the embedding for each grid point of the 2D codebook is learned during training.

**Comment by LinfengYuan1997** [comment]
Thanks for you quick response~

**Comment by LinfengYuan1997** [comment]
Could you please refer me to the code involving the translation and interpolation process from the floating point coordinates to the embeddings. Your project code is detailed and a bit large in scale.

**Comment by joellliu** [comment]
Hi this is the interpolation code
https://github.com/amazon-science/polygon-transformer/blob/52b83d8eaec7893119ae9885d5e33b5f9f95c83a/models/polyformer/unify_transformer.py#L1311

**Comment by LinfengYuan1997** [comment]
> Hi this is the interpolation code
> 
> https://github.com/amazon-science/polygon-transformer/blob/52b83d8eaec7893119ae9885d5e33b5f9f95c83a/models/polyformer/unify_transformer.py#L1311

Many thanks!!!
