### ISSUE TITLE
The code sometimes like Python 2

### ISSUE THREAD

**Issue by IL98** [amazon-science/polygon-transformer#8]
Hi! The python 3.7 is said in the Readme. But some parts of the code reminds Python2, like prints (e.g. [there](https://github.com/amazon-science/polygon-transformer/blob/52b83d8eaec7893119ae9885d5e33b5f9f95c83a/refer/evaluation/bleu/bleu_scorer.py#L242))

Could you explain why is that? It causes the mistakes at some places (like in notebooks in refer)

**Comment by joellliu** [comment]
We only use the refer repo for data loading in data preprocessing. Other than that our codes are based on python 3.7.
