### ISSUE TITLE
Generation of multi-object sequence label

### ISSUE THREAD

**Issue by big-feather** [amazon-science/polygon-transformer#9]
Dear Author, I would like to know how to generate sequence labels with <sep> intervals when there are multiple objects in the mask or a single object with multiple disjointed areas？If it's convenient, could you please point out which part of the code implements this?

**Comment by joellliu** [comment]
Hi, we currently do support the scenario where a single object has multiple disjointed areas, and the polygons for each area are concatenated with the separator token in between.
https://github.com/amazon-science/polygon-transformer/blob/52b83d8eaec7893119ae9885d5e33b5f9f95c83a/data/poly_utils.py#L21

**Comment by big-feather** [comment]
Thanks for your quick reply!
